pipeline {
    agent none
    stages{
        stage("build"){
            agent{ 
                docker{ 
                    image 'maven:3.9.8-sapmachine-21' 
                    args '-v$HOME/.m2:/root/.m2' 
                } 
            }
            steps{ 
                echo 'building worker app' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            }
        }
        stage("test"){
            agent{ 
                docker{ 
                    image 'maven:3.9.8-sapmachine-21' 
                    args '-v$HOME/.m2:/root/.m2' 
                } 
            }
            steps{ 
                echo 'running unit tests on worker app' 
                dir('worker'){ 
                  sh 'mvn clean test' 
                } 
            }
        }
        stage("package"){
            agent{ 
                docker{ 
                    image 'maven:3.9.8-sapmachine-21' 
                    args '-v$HOME/.m2:/root/.m2' 
                } 
            }
            steps{ 
                echo 'packaging worker app into a jarfile'
                dir('worker'){ 
                  sh 'mvn package -DskipTests' 
                  archiveArtifacts artifacts: '**/target/*.jar', fingerprint:  true 
                } 
            } 
        }        
        stage('Docker Build & Push') {
            agent any                        
            steps {
                echo 'build docker image and push to docker hub'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                        def workerImage = docker.build("raju2128/workerapp:${env.BUILD_NUMBER}", "./worker")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}")
                        workerImage.push("latest")
                    }
                }
            }        
        }
    }
    post{ 
        always{ 
            echo 'the job is complete' 

    }
  }
}






// pipeline {
//     agent{
//         docker{
//             image 'maven:3.9.8-sapmachine-21'
//             args '-v $HOME/.m2:/root/.m2'
//         }
//     }
    
//     tools{
//         maven 'maven 3.9.8'
//     }
//     stages{
//         stage("build"){
//             when{
//                 changeset "**/worker/**"
//             }

//             steps{
//                 echo 'Compiling worker app'
//                 dir('worker') {
//                     sh 'mvn compile'
//                 }
//             }
//         }
//         stage("test"){
//             when{
//                 changeset "**/worker/**"
//             }

//             steps{
//                 echo 'Running Unit Tests on Worker App' 
//                 dir('worker') {
//                     sh 'mvn clean test'
//                 }               
//             }
//         }
//         stage("package"){
//             when{
//                 // branch 'master'
//                 changeset "**/worker/**"
//             }
//             steps{
//                 echo "Packaging worker app"
//                 dir('worker') {
//                     sh 'mvn package -DskipTests'
//                     archiveArtifacts artifacts: '**/*.jar', fingerprint: true
//                 }
//             }
//         }
//     }
//     post{
//         always{
//             echo "BuildingMultibranchpiPelineforWorkerisCompleted......."
//         }
//         failure{
//             slackSend (channel: 'instavote-cd', message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
//         }
//         success{
//             slackSend (channel: 'instavote-cd', message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
//         }
//     }    
// }

