pipeline {
    agent any
    
    tools{
        maven 'maven 3.9.8'
    }
    stages{
        stage("build"){
            steps{
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage("test"){
            steps{
                echo 'Running Unit Tests on Worker App' 
                dir('worker') {
                    sh 'mvn clean test'
                }               
            }
        }
        stage("package"){
            steps{
                echo "Packaging worker app"
                dir('worker') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
    post{
        always{
            archiveArtifacts artifacts: '**/*.jar', fingerprint: true
            echo "BuildingMultibranchpiPelineforWorkerisCompleted......."
        }
    }    
}








// pipeline { 
//     agent{ 
//        docker{ 
//          image 'maven:3.9.8-sapmachine-21' 
//          args '-v $HOME/.m2:/root/.m2' 
//        } 
//     } 
//     stages{ 
//         stage('build'){ 
//             steps{ 
//                 echo 'building worker app' 
//                 dir('worker'){ 
//                   sh 'mvn compile' 
//                 } 
//             } 
//         } 
//         stage('test'){ 
//             steps{ 
//                 echo 'running unit tests on worker app' 
//                 dir('worker'){ 
//                   sh 'mvn clean test' 
//                 } 
//             } 
//         } 
//         stage('package'){ 
//             steps{ 
//                 echo 'packaging worker app into a jarfile'
//                 dir('worker'){ 
//                   sh 'mvn package -DskipTests' 
//                   archiveArtifacts artifacts: '**/target/*.jar', fingerprint:  true 
//                 } 
//             } 
//         } 
//     }
//     post{ 
//         always{ 
//             echo 'the job is complete' 

//     }
//   }
// }
